name: diffusion-experiments
channels:
- conda-forge
- main
- nvidia
- pytorch
- xformers
dependencies:
- _libgcc_mutex=0.1=main
- _openmp_mutex=5.1=1_gnu
- abseil-cpp=20211102.0=hd4dd3e8_0
- accelerate=0.19.0=pyhd8ed1ab_0
- aiohttp=3.8.3=py310h5eee18b_0
- aiosignal=1.2.0=pyhd3eb1b0_0
- anyio=3.5.0=py310h06a4308_0
- appdirs=1.4.4=pyhd3eb1b0_0
- argon2-cffi=21.3.0=pyhd3eb1b0_0
- argon2-cffi-bindings=21.2.0=py310h7f8727e_0
- arrow-cpp=11.0.0=py310h7516544_0
- astroid=2.14.2=py310h06a4308_0
- asttokens=2.0.5=pyhd3eb1b0_0
- async-timeout=4.0.2=py310h06a4308_0
- attrs=22.1.0=py310h06a4308_0
- aws-c-common=0.4.57=he6710b0_1
- aws-c-event-stream=0.1.6=h2531618_5
- aws-checksums=0.1.9=he6710b0_0
- aws-sdk-cpp=1.8.185=hce553d0_0
- babel=2.11.0=py310h06a4308_0
- backcall=0.2.0=pyhd3eb1b0_0
- beautifulsoup4=4.12.2=py310h06a4308_0
- black=23.3.0=py310h06a4308_0
- blas=1.0=mkl
- bleach=4.1.0=pyhd3eb1b0_0
- boost-cpp=1.73.0=h7f8727e_12
- bottleneck=1.3.5=py310ha9d4c09_0
- brotli=1.0.9=h5eee18b_7
- brotli-bin=1.0.9=h5eee18b_7
- brotlipy=0.7.0=py310h7f8727e_1002
- bzip2=1.0.8=h7b6447c_0
- c-ares=1.19.0=h5eee18b_0
- ca-certificates=2023.01.10=h06a4308_0
- certifi=2022.12.7=py310h06a4308_0
- cffi=1.15.1=py310h5eee18b_3
- charset-normalizer=2.0.4=pyhd3eb1b0_0
- click=8.1.3=unix_pyhd8ed1ab_2
- colorama=0.4.6=py310h06a4308_0
- comm=0.1.2=py310h06a4308_0
- contourpy=1.0.5=py310hdb19cb5_0
- cryptography=39.0.1=py310h9ce1e76_0
- cuda-cudart=11.8.89=0
- cuda-cupti=11.8.87=0
- cuda-libraries=11.8.0=0
- cuda-nvrtc=11.8.89=0
- cuda-nvtx=11.8.86=0
- cuda-runtime=11.8.0=0
- cycler=0.11.0=pyhd3eb1b0_0
- datasets=2.10.1=py310h06a4308_0
- dbus=1.13.18=hb2f20db_0
- debugpy=1.5.1=py310h295c915_0
- decorator=5.1.1=pyhd3eb1b0_0
- defusedxml=0.7.1=pyhd3eb1b0_0
- diffusers=0.16.1=pyhd8ed1ab_0
- dill=0.3.6=py310h06a4308_0
- docker-pycreds=0.4.0=py_0
- entrypoints=0.4=py310h06a4308_0
- executing=0.8.3=pyhd3eb1b0_0
- expat=2.4.9=h6a678d5_0
- ffmpeg=4.3.2=hca11adc_0
- filelock=3.9.0=py310h06a4308_0
- fontconfig=2.14.1=h4c34cd2_2
- fonttools=4.25.0=pyhd3eb1b0_0
- freetype=2.12.1=h4a9f257_0
- frozenlist=1.3.3=py310h5eee18b_0
- fsspec=2023.4.0=py310h06a4308_0
- gflags=2.2.2=he6710b0_0
- giflib=5.2.1=h5eee18b_3
- gitdb=4.0.10=pyhd8ed1ab_0
- gitpython=3.1.31=pyhd8ed1ab_0
- glib=2.69.1=he621ea3_2
- glog=0.5.0=h2531618_0
- gmp=6.2.1=h295c915_3
- gmpy2=2.1.2=py310heeb90bb_0
- gnutls=3.6.15=he1e5248_0
- grpc-cpp=1.46.1=h33aed49_1
- gst-plugins-base=1.14.1=h6a678d5_1
- gstreamer=1.14.1=h5eee18b_1
- huggingface_hub=0.14.1=py310h06a4308_0
- icu=58.2=he6710b0_3
- idna=3.4=py310h06a4308_0
- importlib-metadata=6.0.0=py310h06a4308_0
- intel-openmp=2021.4.0=h06a4308_3561
- ipykernel=6.19.2=py310h2f386ee_0
- ipympl=0.9.3=pyhd8ed1ab_0
- ipython=8.12.0=py310h06a4308_0
- ipython_genutils=0.2.0=pyhd3eb1b0_1
- ipywidgets=8.0.4=py310h06a4308_0
- isort=5.12.0=pyhd8ed1ab_1
- jedi=0.18.1=py310h06a4308_1
- jinja2=3.1.2=py310h06a4308_0
- joblib=1.2.0=py310h06a4308_0
- jpeg=9e=h5eee18b_1
- json5=0.9.6=pyhd3eb1b0_0
- jsonschema=4.17.3=py310h06a4308_0
- jupyter=1.0.0=py310h06a4308_8
- jupyter_client=8.1.0=py310h06a4308_0
- jupyter_console=6.6.3=py310h06a4308_0
- jupyter_core=5.3.0=py310h06a4308_0
- jupyter_server=1.23.4=py310h06a4308_0
- jupyterlab=3.5.3=py310h06a4308_0
- jupyterlab_pygments=0.1.2=py_0
- jupyterlab_server=2.22.0=py310h06a4308_0
- jupyterlab_widgets=3.0.5=py310h06a4308_0
- kiwisolver=1.4.4=py310h6a678d5_0
- krb5=1.19.4=h568e23c_0
- lame=3.100=h7b6447c_0
- lazy-object-proxy=1.6.0=py310h7f8727e_0
- lcms2=2.12=h3be6417_0
- ld_impl_linux-64=2.38=h1181459_1
- lerc=3.0=h295c915_0
- libblas=3.9.0=12_linux64_mkl
- libboost=1.73.0=h28710b8_12
- libbrotlicommon=1.0.9=h5eee18b_7
- libbrotlidec=1.0.9=h5eee18b_7
- libbrotlienc=1.0.9=h5eee18b_7
- libcblas=3.9.0=12_linux64_mkl
- libclang=14.0.6=default_hc6dbbc7_1
- libclang13=14.0.6=default_he11475f_1
- libcublas=11.11.3.6=0
- libcufft=10.9.0.58=0
- libcufile=1.6.1.9=0
- libcurand=10.3.2.106=0
- libcurl=7.88.1=h91b91d3_0
- libcusolver=11.4.1.48=0
- libcusparse=11.7.5.86=0
- libdeflate=1.17=h5eee18b_0
- libedit=3.1.20221030=h5eee18b_0
- libev=4.33=h7f8727e_1
- libevent=2.1.12=h8f2d780_0
- libffi=3.4.2=h6a678d5_6
- libgcc-ng=11.2.0=h1234567_1
- libgfortran-ng=12.2.0=h69a702a_19
- libgfortran5=12.2.0=h337968e_19
- libgomp=11.2.0=h1234567_1
- libiconv=1.16=h7f8727e_2
- libidn2=2.3.2=h7f8727e_0
- liblapack=3.9.0=12_linux64_mkl
- libllvm14=14.0.6=hdb19cb5_2
- libnghttp2=1.46.0=hce63b2e_0
- libnpp=11.8.0.86=0
- libnvjpeg=11.9.0.86=0
- libpng=1.6.39=h5eee18b_0
- libpq=12.9=h16c4e8d_3
- libprotobuf=3.20.3=he621ea3_0
- libsodium=1.0.18=h7b6447c_0
- libssh2=1.10.0=h8f2d780_0
- libstdcxx-ng=11.2.0=h1234567_1
- libtasn1=4.19.0=h5eee18b_0
- libthrift=0.15.0=hcc01f38_0
- libtiff=4.5.0=h6a678d5_2
- libunistring=0.9.10=h27cfd23_0
- libuuid=1.41.5=h5eee18b_0
- libwebp=1.2.4=h11a3e52_1
- libwebp-base=1.2.4=h5eee18b_1
- libxcb=1.15=h7f8727e_0
- libxkbcommon=1.0.1=h5eee18b_1
- libxml2=2.10.3=hcbfbd50_0
- libxslt=1.1.37=h2085143_0
- lxml=4.9.2=py310h5eee18b_0
- lz4-c=1.9.4=h6a678d5_0
- markupsafe=2.1.1=py310h7f8727e_0
- matplotlib=3.7.1=py310h06a4308_1
- matplotlib-base=3.7.1=py310h1128e8f_1
- matplotlib-inline=0.1.6=py310h06a4308_0
- mccabe=0.7.0=pyhd3eb1b0_0
- mistune=0.8.4=py310h7f8727e_1000
- mkl=2021.4.0=h06a4308_640
- mkl-service=2.4.0=py310h7f8727e_0
- mkl_fft=1.3.1=py310hd6ae3a3_0
- mkl_random=1.2.2=py310h00e6091_0
- mpc=1.1.0=h10f8cd9_1
- mpfr=4.0.2=hb69a4c5_1
- mpmath=1.2.1=py310h06a4308_0
- multidict=6.0.2=py310h5eee18b_0
- multiprocess=0.70.14=py310h06a4308_0
- munkres=1.1.4=py_0
- mypy_extensions=0.4.3=py310h06a4308_0
- nbclassic=0.5.5=py310h06a4308_0
- nbclient=0.5.13=py310h06a4308_0
- nbconvert=6.5.4=py310h06a4308_0
- nbformat=5.7.0=py310h06a4308_0
- ncurses=6.4=h6a678d5_0
- nest-asyncio=1.5.6=py310h06a4308_0
- nettle=3.7.3=hbbd107a_1
- networkx=2.8.4=py310h06a4308_1
- notebook=6.5.4=py310h06a4308_0
- notebook-shim=0.2.2=py310h06a4308_0
- nspr=4.33=h295c915_0
- nss=3.74=h0370c37_0
- numexpr=2.8.4=py310h8879344_0
- numpy=1.24.3=py310hd5efca6_0
- numpy-base=1.24.3=py310h8e6c178_0
- openh264=2.1.1=h4ff587b_0
- openssl=1.1.1t=h7f8727e_0
- orc=1.7.4=hb3bc3d3_1
- packaging=23.0=py310h06a4308_0
- pandas=1.5.3=py310h1128e8f_0
- pandocfilters=1.5.0=pyhd3eb1b0_0
- parso=0.8.3=pyhd3eb1b0_0
- pathspec=0.10.3=py310h06a4308_0
- pathtools=0.1.2=pyhd3eb1b0_1
- pcre=8.45=h295c915_0
- pexpect=4.8.0=pyhd3eb1b0_3
- pickleshare=0.7.5=pyhd3eb1b0_1003
- pillow=9.4.0=py310h6a678d5_0
- pip=23.0.1=py310h06a4308_0
- platformdirs=2.5.2=py310h06a4308_0
- ply=3.11=py310h06a4308_0
- pooch=1.4.0=pyhd3eb1b0_0
- prometheus_client=0.14.1=py310h06a4308_0
- prompt-toolkit=3.0.36=py310h06a4308_0
- prompt_toolkit=3.0.36=hd3eb1b0_0
- protobuf=3.20.3=py310h6a678d5_0
- psutil=5.9.0=py310h5eee18b_0
- ptyprocess=0.7.0=pyhd3eb1b0_2
- pure_eval=0.2.2=pyhd3eb1b0_0
- pyarrow=11.0.0=py310h468efa6_0
- pycparser=2.21=pyhd3eb1b0_0
- pygments=2.11.2=pyhd3eb1b0_0
- pylint=2.16.2=py310h06a4308_0
- pyopenssl=23.0.0=py310h06a4308_0
- pyparsing=3.0.9=py310h06a4308_0
- pyqt=5.15.7=py310h6a678d5_1
- pyqt5-sip=12.11.0=py310h6a678d5_1
- pyrsistent=0.18.0=py310h7f8727e_0
- pysocks=1.7.1=py310h06a4308_0
- python=3.10.11=h7a1cb2a_2
- python-dateutil=2.8.2=pyhd3eb1b0_0
- python-fastjsonschema=2.16.2=py310h06a4308_0
- python-xxhash=2.0.2=py310h5eee18b_1
- python_abi=3.10=2_cp310
- pytorch=2.0.0=py3.10_cuda11.8_cudnn8.7.0_0
- pytorch-cuda=11.8=h7e8668a_5
- pytorch-mutex=1.0=cuda
- pytz=2022.7=py310h06a4308_0
- pyyaml=6.0=py310h5eee18b_1
- pyzmq=25.0.2=py310h6a678d5_0
- qt-main=5.15.2=h8373d8f_8
- qt-webengine=5.15.9=hbbf29b9_6
- qtconsole=5.4.2=py310h06a4308_0
- qtpy=2.2.0=py310h06a4308_0
- qtwebkit=5.212=h3fafdc1_5
- re2=2022.04.01=h295c915_0
- readline=8.2=h5eee18b_0
- regex=2022.7.9=py310h5eee18b_0
- requests=2.29.0=py310h06a4308_0
- responses=0.13.3=pyhd3eb1b0_0
- sacremoses=0.0.43=pyhd3eb1b0_0
- scipy=1.10.1=py310hd5efca6_0
- send2trash=1.8.0=pyhd3eb1b0_1
- sentry-sdk=1.21.1=pyhd8ed1ab_0
- setproctitle=1.2.2=py310h7f8727e_0
- setuptools=66.0.0=py310h06a4308_0
- sip=6.6.2=py310h6a678d5_0
- six=1.16.0=pyhd3eb1b0_1
- smmap=3.0.5=pyh44b312d_0
- snappy=1.1.9=h295c915_0
- sniffio=1.2.0=py310h06a4308_1
- soupsieve=2.4=py310h06a4308_0
- sqlite=3.41.2=h5eee18b_0
- stack_data=0.2.0=pyhd3eb1b0_0
- sympy=1.11.1=py310h06a4308_0
- terminado=0.17.1=py310h06a4308_0
- tinycss2=1.2.1=py310h06a4308_0
- tk=8.6.12=h1ccaba5_0
- tokenizers=0.11.4=py310h3dcd8bd_1
- toml=0.10.2=pyhd3eb1b0_0
- tomli=2.0.1=py310h06a4308_0
- tomlkit=0.11.1=py310h06a4308_0
- torch-fidelity=0.3.0=pyhd8ed1ab_0
- torchinfo=1.7.2=pyhd8ed1ab_0
- torchtriton=2.0.0=py310
- torchvision=0.15.0=py310_cu118
- tornado=6.2=py310h5eee18b_0
- tqdm=4.65.0=py310h2f386ee_0
- traitlets=5.7.1=py310h06a4308_0
- transformers=4.29.2=py310h06a4308_0
- typing-extensions=4.5.0=py310h06a4308_0
- typing_extensions=4.5.0=py310h06a4308_0
- tzdata=2023c=h04d1e81_0
- urllib3=1.26.15=py310h06a4308_0
- utf8proc=2.6.1=h27cfd23_0
- wandb=0.15.2=pyhd8ed1ab_0
- wcwidth=0.2.5=pyhd3eb1b0_0
- webencodings=0.5.1=py310h06a4308_1
- websocket-client=0.58.0=py310h06a4308_4
- wheel=0.38.4=py310h06a4308_0
- widgetsnbextension=4.0.5=py310h06a4308_0
- wrapt=1.14.1=py310h5eee18b_0
- x264=1!161.3030=h7f98852_1
- xformers=0.0.19=py310_cu11.8.0_pyt2.0.0
- xxhash=0.8.0=h7f8727e_3
- xz=5.2.10=h5eee18b_1
- yaml=0.2.5=h7b6447c_0
- yarl=1.8.1=py310h5eee18b_0
- zeromq=4.3.4=h2531618_0
- zipp=3.11.0=py310h06a4308_0
- zlib=1.2.13=h5eee18b_0
- zstd=1.5.5=hc292b87_0

