name: 
channels:
- conda-forge
- huggingface
- nvidia
- pytorch
- xformers
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_kmp_llvm
- accelerate=0.20.3=pyhd8ed1ab_0
- aiohttp=3.8.4=py310h2372a71_1
- aiosignal=1.3.1=pyhd8ed1ab_0
- alsa-lib=1.2.8=h166bdaf_0
- antlr-python-runtime=4.9.3=pyhd8ed1ab_1
- anyio=3.7.0=pyhd8ed1ab_1
- appdirs=1.4.4=pyh9f0ad1d_0
- argon2-cffi=21.3.0=pyhd8ed1ab_0
- argon2-cffi-bindings=21.2.0=py310h5764c6d_3
- astroid=2.15.5=py310hff52083_0
- asttokens=2.2.1=pyhd8ed1ab_0
- async-timeout=4.0.2=pyhd8ed1ab_0
- atk-1.0=2.38.0=hd4edc92_1
- attr=2.5.1=h166bdaf_1
- attrs=23.1.0=pyh71513ae_1
- aws-c-auth=0.6.28=hccec9ca_5
- aws-c-cal=0.5.27=hf85dbcb_0
- aws-c-common=0.8.20=hd590300_0
- aws-c-compression=0.2.17=h4b87b72_0
- aws-c-event-stream=0.3.0=hc5de78f_6
- aws-c-http=0.7.8=h412fb1b_4
- aws-c-io=0.13.26=h0d05201_0
- aws-c-mqtt=0.8.13=ha5d9b87_2
- aws-c-s3=0.3.4=h95e21fb_5
- aws-c-sdkutils=0.1.10=h4b87b72_0
- aws-checksums=0.1.16=h4b87b72_0
- aws-crt-cpp=0.20.2=h5289e1f_9
- aws-sdk-cpp=1.10.57=h8101662_14
- backcall=0.2.0=pyh9f0ad1d_0
- backports=1.0=pyhd8ed1ab_3
- backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
- beautifulsoup4=4.12.2=pyha770c72_0
- black=23.3.0=py310hff52083_1
- blas=1.0=mkl
- bleach=6.0.0=pyhd8ed1ab_0
- brotli=1.0.9=h166bdaf_8
- brotli-bin=1.0.9=h166bdaf_8
- bzip2=1.0.8=h7f98852_4
- c-ares=1.19.1=hd590300_0
- ca-certificates=2023.5.7=hbcca054_0
- cairo=1.16.0=ha61ee94_1014
- certifi=2023.5.7=pyhd8ed1ab_0
- cffi=1.15.1=py310h255011f_3
- cfgv=3.3.1=pyhd8ed1ab_0
- charset-normalizer=3.1.0=pyhd8ed1ab_0
- click=8.1.3=unix_pyhd8ed1ab_2
- colorama=0.4.6=pyhd8ed1ab_0
- colorlog=6.7.0=py310hff52083_1
- comm=0.1.3=pyhd8ed1ab_0
- contourpy=1.1.0=py310hd41b1e2_0
- cuda-cudart=11.8.89=0
- cuda-cupti=11.8.87=0
- cuda-libraries=11.8.0=0
- cuda-nvrtc=11.8.89=0
- cuda-nvtx=11.8.86=0
- cuda-runtime=11.8.0=0
- cycler=0.11.0=pyhd8ed1ab_0
- dataclasses=0.8=pyhc8e2a94_3
- datasets=2.13.0=py_0
- dbus=1.13.6=h5008d03_3
- debugpy=1.6.7=py310heca2aa9_0
- decorator=5.1.1=pyhd8ed1ab_0
- defusedxml=0.7.1=pyhd8ed1ab_0
- diffusers=0.18.2=pyhd8ed1ab_0
- dill=0.3.6=pyhd8ed1ab_1
- distlib=0.3.6=pyhd8ed1ab_0
- docker-pycreds=0.4.0=py_0
- entrypoints=0.4=pyhd8ed1ab_0
- exceptiongroup=1.1.1=pyhd8ed1ab_0
- executing=1.2.0=pyhd8ed1ab_0
- expat=2.5.0=hcb278e6_1
- ffmpeg=4.3=hf484d3e_0
- fftw=3.3.10=nompi_hc118613_108
- filelock=3.12.2=pyhd8ed1ab_0
- flit-core=3.9.0=pyhd8ed1ab_0
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=3.000=h77eed37_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- font-ttf-ubuntu=0.83=hab24e00_0
- fontconfig=2.14.2=h14ed4e7_0
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- fonttools=4.40.0=py310h2372a71_0
- freetype=2.12.1=hca18f0e_1
- fribidi=1.0.10=h36c2ea0_0
- frozenlist=1.3.3=py310h5764c6d_0
- fsspec=2023.6.0=pyh1a96a4e_0
- gdk-pixbuf=2.42.10=h05c8ddd_0
- gettext=0.21.1=h27087fc_0
- gflags=2.2.2=he1b5a44_1004
- giflib=5.2.1=h0b41bf4_3
- gitdb=4.0.10=pyhd8ed1ab_0
- gitpython=3.1.31=pyhd8ed1ab_0
- glib=2.76.3=hfc55251_0
- glib-tools=2.76.3=hfc55251_0
- glog=0.6.0=h6f12383_0
- gmp=6.2.1=h58526e2_0
- gmpy2=2.1.2=py310h3ec546c_1
- gnutls=3.6.13=h85f3911_1
- graphite2=1.3.13=h58526e2_1001
- graphviz=7.1.0=h2e5815a_0
- gst-plugins-base=1.22.0=h4243ec0_2
- gstreamer=1.22.0=h25f0c4b_2
- gstreamer-orc=0.4.34=hd590300_0
- gtk2=2.24.33=h90689f9_2
- gts=0.7.6=h977cf35_4
- harfbuzz=6.0.0=h8e241bc_0
- huggingface_hub=0.15.1=py_0
- hydra-colorlog=1.2.0=pyhd8ed1ab_1
- hydra-core=1.3.2=pyhd8ed1ab_0
- icu=70.1=h27087fc_0
- identify=2.5.24=pyhd8ed1ab_0
- idna=3.4=pyhd8ed1ab_0
- importlib-metadata=6.7.0=pyha770c72_0
- importlib_metadata=6.7.0=hd8ed1ab_0
- importlib_resources=5.12.0=pyhd8ed1ab_0
- ipykernel=6.23.1=pyh210e3f2_0
- ipython=8.14.0=pyh41d4057_0
- ipython_genutils=0.2.0=py_1
- ipywidgets=8.0.6=pyhd8ed1ab_0
- isort=5.12.0=pyhd8ed1ab_1
- jack=1.9.22=h11f4161_0
- jedi=0.18.2=pyhd8ed1ab_0
- jinja2=3.1.2=pyhd8ed1ab_1
- joblib=1.2.0=pyhd8ed1ab_0
- jpeg=9e=h0b41bf4_3
- jsonschema=4.17.3=pyhd8ed1ab_0
- jupyter=1.0.0=py310hff52083_8
- jupyter_client=8.2.0=pyhd8ed1ab_0
- jupyter_console=6.6.3=pyhd8ed1ab_0
- jupyter_core=5.3.1=py310hff52083_0
- jupyter_events=0.6.3=pyhd8ed1ab_0
- jupyter_server=2.6.0=pyhd8ed1ab_0
- jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
- jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
- jupyterlab_widgets=3.0.7=pyhd8ed1ab_1
- keyutils=1.6.1=h166bdaf_0
- kiwisolver=1.4.4=py310hbf28c38_1
- krb5=1.20.1=h81ceb04_0
- lame=3.100=h166bdaf_1003
- lazy-object-proxy=1.9.0=py310h1fa729e_0
- lcms2=2.15=hfd0df8a_0
- ld_impl_linux-64=2.40=h41732ed_0
- lerc=4.0.0=h27087fc_0
- libabseil=20230125.2=cxx17_h59595ed_2
- libarrow=12.0.0=hc00ebf5_8_cpu
- libblas=3.9.0=16_linux64_mkl
- libbrotlicommon=1.0.9=h166bdaf_8
- libbrotlidec=1.0.9=h166bdaf_8
- libbrotlienc=1.0.9=h166bdaf_8
- libcap=2.67=he9d0100_0
- libcblas=3.9.0=16_linux64_mkl
- libclang=15.0.7=default_h7634d5b_2
- libclang13=15.0.7=default_h9986a30_2
- libcrc32c=1.1.2=h9c3ff4c_0
- libcublas=11.11.3.6=0
- libcufft=10.9.0.58=0
- libcufile=1.6.1.9=0
- libcups=2.3.3=h36d4200_3
- libcurand=10.3.2.106=0
- libcurl=8.1.2=h409715c_0
- libcusolver=11.4.1.48=0
- libcusparse=11.7.5.86=0
- libdb=6.2.32=h9c3ff4c_0
- libdeflate=1.17=h0b41bf4_0
- libedit=3.1.20191231=he28a2e2_2
- libev=4.33=h516909a_1
- libevent=2.1.10=h28343ad_4
- libexpat=2.5.0=hcb278e6_1
- libffi=3.4.2=h7f98852_5
- libflac=1.4.2=h27087fc_0
- libgcc-ng=13.1.0=he5830b7_0
- libgcrypt=1.10.1=h166bdaf_0
- libgd=2.3.3=h5aea950_4
- libgfortran-ng=13.1.0=h69a702a_0
- libgfortran5=13.1.0=h15d22d2_0
- libglib=2.76.3=hebfc3b9_0
- libgoogle-cloud=2.11.0=hac9eb74_1
- libgpg-error=1.47=h71f35ed_0
- libgrpc=1.54.2=hb20ce57_2
- libhwloc=2.9.1=hd6dc26d_0
- libiconv=1.17=h166bdaf_0
- liblapack=3.9.0=16_linux64_mkl
- libllvm15=15.0.7=hadd5161_1
- libnghttp2=1.52.0=h61bc06f_0
- libnpp=11.8.0.86=0
- libnsl=2.0.0=h7f98852_0
- libnuma=2.0.16=h0b41bf4_1
- libnvjpeg=11.9.0.86=0
- libogg=1.3.4=h7f98852_1
- libopus=1.3.1=h7f98852_1
- libpng=1.6.39=h753d276_0
- libpq=15.3=hbcd7760_1
- libprotobuf=3.21.12=h3eb15da_0
- librsvg=2.54.4=h7abd40a_0
- libsndfile=1.2.0=hb75c966_0
- libsodium=1.0.18=h36c2ea0_1
- libsqlite=3.42.0=h2797004_0
- libssh2=1.11.0=h0841786_0
- libstdcxx-ng=13.1.0=hfd8a6a1_0
- libsystemd0=253=h8c4010b_1
- libthrift=0.18.1=h5e4af38_0
- libtiff=4.5.0=h6adf6a1_2
- libtool=2.4.7=h27087fc_0
- libudev1=253=h0b41bf4_1
- libutf8proc=2.8.0=h166bdaf_0
- libuuid=2.38.1=h0b41bf4_0
- libvorbis=1.3.7=h9c3ff4c_0
- libwebp=1.2.4=h1daa5a0_1
- libwebp-base=1.2.4=h166bdaf_0
- libxcb=1.13=h7f98852_1004
- libxkbcommon=1.5.0=h79f4944_1
- libxml2=2.10.3=hca2bb57_4
- libzlib=1.2.13=hd590300_5
- llvm-openmp=16.0.6=h4dfa4b3_0
- lz4-c=1.9.4=hcb278e6_0
- markupsafe=2.1.3=py310h2372a71_0
- matplotlib=3.7.1=py310hff52083_0
- matplotlib-base=3.7.1=py310he60537e_0
- matplotlib-inline=0.1.6=pyhd8ed1ab_0
- mccabe=0.7.0=pyhd8ed1ab_0
- mistune=3.0.0=pyhd8ed1ab_0
- mkl=2022.2.1=h84fe81f_16997
- mpc=1.3.1=hfe3b2da_0
- mpfr=4.2.0=hb012696_0
- mpg123=1.31.3=hcb278e6_0
- mpmath=1.3.0=pyhd8ed1ab_0
- multidict=6.0.4=py310h1fa729e_0
- multiprocess=0.70.14=py310h5764c6d_3
- munkres=1.1.4=pyh9f0ad1d_0
- mypy_extensions=1.0.0=pyha770c72_0
- mysql-common=8.0.33=hf1915f5_0
- mysql-libs=8.0.33=hca2cd23_0
- nbclassic=1.0.0=pyhb4ecaf3_1
- nbclient=0.8.0=pyhd8ed1ab_0
- nbconvert=7.6.0=pyhd8ed1ab_0
- nbconvert-core=7.6.0=pyhd8ed1ab_0
- nbconvert-pandoc=7.6.0=pyhd8ed1ab_0
- nbformat=5.9.0=pyhd8ed1ab_0
- ncurses=6.4=hcb278e6_0
- nest-asyncio=1.5.6=pyhd8ed1ab_0
- nettle=3.6=he412f7d_0
- networkx=3.1=pyhd8ed1ab_0
- ninja=1.11.1=h924138e_0
- nodeenv=1.8.0=pyhd8ed1ab_0
- notebook=6.5.4=pyha770c72_0
- notebook-shim=0.2.3=pyhd8ed1ab_0
- nspr=4.35=h27087fc_0
- nss=3.89=he45b914_0
- numpy=1.25.0=py310ha4c1d20_0
- omegaconf=2.3.0=pyhd8ed1ab_0
- openh264=2.1.1=h780b84a_0
- openjpeg=2.5.0=hfec8fc6_2
- openssl=3.1.1=hd590300_1
- orc=1.8.4=h2f23424_0
- overrides=7.3.1=pyhd8ed1ab_0
- packaging=23.1=pyhd8ed1ab_0
- pandas=2.0.2=py310h7cbd5c2_0
- pandoc=3.1.3=h32600fe_0
- pandocfilters=1.5.0=pyhd8ed1ab_0
- pango=1.50.14=hd33c08f_0
- parso=0.8.3=pyhd8ed1ab_0
- pathspec=0.11.1=pyhd8ed1ab_0
- pathtools=0.1.2=py_1
- pcre2=10.40=hc3806b6_0
- pexpect=4.8.0=pyh1a96a4e_2
- pickleshare=0.7.5=py_1003
- pillow=9.4.0=py310h023d228_1
- pip=23.1.2=pyhd8ed1ab_0
- pixman=0.40.0=h36c2ea0_0
- pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
- platformdirs=3.6.0=pyhd8ed1ab_0
- ply=3.11=py_1
- pooch=1.7.0=pyha770c72_3
- pre-commit=3.3.3=pyha770c72_0
- prometheus_client=0.17.0=pyhd8ed1ab_0
- prompt-toolkit=3.0.38=pyha770c72_0
- prompt_toolkit=3.0.38=hd8ed1ab_0
- protobuf=4.21.12=py310heca2aa9_0
- psutil=5.9.5=py310h1fa729e_0
- pthread-stubs=0.4=h36c2ea0_1001
- ptyprocess=0.7.0=pyhd3deb0d_0
- pulseaudio=16.1=hcb278e6_3
- pulseaudio-client=16.1=h5195f5e_3
- pulseaudio-daemon=16.1=ha8d29e2_3
- pure_eval=0.2.2=pyhd8ed1ab_0
- pyarrow=12.0.0=py310h0576679_8_cpu
- pycparser=2.21=pyhd8ed1ab_0
- pygments=2.15.1=pyhd8ed1ab_0
- pylint=2.17.4=pyhd8ed1ab_0
- pyparsing=3.1.0=pyhd8ed1ab_0
- pyqt=5.15.7=py310hab646b1_3
- pyqt5-sip=12.11.0=py310heca2aa9_3
- pyrsistent=0.19.3=py310h1fa729e_0
- pysocks=1.7.1=pyha2e5f31_6
- python=3.10.11=he550d4f_0_cpython
- python-dateutil=2.8.2=pyhd8ed1ab_0
- python-fastjsonschema=2.17.1=pyhd8ed1ab_0
- python-graphviz=0.20.1=pyh22cad53_0
- python-json-logger=2.0.7=pyhd8ed1ab_0
- python-tzdata=2023.3=pyhd8ed1ab_0
- python-xxhash=3.2.0=py310h1fa729e_0
- python_abi=3.10=3_cp310
- pytorch=2.0.1=py3.10_cuda11.8_cudnn8.7.0_0
- pytorch-cuda=11.8=h7e8668a_5
- pytorch-mutex=1.0=cuda
- pytz=2023.3=pyhd8ed1ab_0
- pyyaml=6.0=py310h5764c6d_5
- pyzmq=25.1.0=py310h5bbb5d0_0
- qt-main=5.15.8=h5d23da1_6
- qtconsole=5.4.3=pyhd8ed1ab_0
- qtconsole-base=5.4.3=pyha770c72_0
- qtpy=2.3.1=pyhd8ed1ab_0
- rdma-core=28.9=h59595ed_1
- re2=2023.03.02=h8c504da_0
- readline=8.2=h8228510_1
- regex=2023.6.3=py310h2372a71_0
- requests=2.31.0=pyhd8ed1ab_0
- rfc3339-validator=0.1.4=pyhd8ed1ab_0
- rfc3986-validator=0.1.1=pyh9f0ad1d_0
- s2n=1.3.45=h06160fa_0
- sacremoses=master=py_0
- safetensors=0.3.1=py310hcb5633a_0
- scipy=1.11.1=py310ha4c1d20_0
- send2trash=1.8.2=pyh41d4057_0
- sentry-sdk=1.21.1=pyhd8ed1ab_0
- setproctitle=1.3.2=py310h5764c6d_1
- setuptools=67.7.2=pyhd8ed1ab_0
- sip=6.7.9=py310hc6cd4ac_0
- six=1.16.0=pyh6c4a22f_0
- smmap=3.0.5=pyh44b312d_0
- snappy=1.1.10=h9fff704_0
- sniffio=1.3.0=pyhd8ed1ab_0
- soupsieve=2.3.2.post1=pyhd8ed1ab_0
- stack_data=0.6.2=pyhd8ed1ab_0
- sympy=1.12=pypyh9d50eac_103
- tbb=2021.9.0=hf52228f_0
- terminado=0.17.1=pyh41d4057_0
- tinycss2=1.2.1=pyhd8ed1ab_0
- tk=8.6.12=h27826a3_0
- tokenizers=0.13.3=py310he1f1126_0
- toml=0.10.2=pyhd8ed1ab_0
- tomli=2.0.1=pyhd8ed1ab_0
- tomlkit=0.11.8=pyha770c72_0
- torch-fidelity=0.3.0=pyhd8ed1ab_0
- torchaudio=2.0.2=py310_cu118
- torchinfo=1.8.0=pyhd8ed1ab_0
- torchtriton=2.0.0=py310
- torchview=0.2.6=pyhd8ed1ab_0
- torchvision=0.15.2=py310_cu118
- tornado=6.3.2=py310h2372a71_0
- tqdm=4.65.0=pyhd8ed1ab_1
- traitlets=5.9.0=pyhd8ed1ab_0
- transformers=4.30.2=pyhd8ed1ab_1
- typing-extensions=4.6.3=hd8ed1ab_0
- typing_extensions=4.6.3=pyha770c72_0
- typing_utils=0.1.0=pyhd8ed1ab_0
- tzdata=2023c=h71feb2d_0
- ucx=1.14.1=hf587318_2
- ukkonen=1.0.1=py310hbf28c38_3
- unicodedata2=15.0.0=py310h5764c6d_0
- urllib3=2.0.3=pyhd8ed1ab_0
- virtualenv=20.23.1=pyhd8ed1ab_0
- wandb=0.15.9=pyhd8ed1ab_0
- wcwidth=0.2.6=pyhd8ed1ab_0
- webencodings=0.5.1=py_1
- websocket-client=1.6.0=pyhd8ed1ab_0
- wheel=0.40.0=pyhd8ed1ab_0
- widgetsnbextension=4.0.7=pyhd8ed1ab_0
- wrapt=1.15.0=py310h1fa729e_0
- xcb-util=0.4.0=h516909a_0
- xcb-util-image=0.4.0=h166bdaf_0
- xcb-util-keysyms=0.4.0=h516909a_0
- xcb-util-renderutil=0.3.9=h166bdaf_0
- xcb-util-wm=0.4.1=h516909a_0
- xformers=0.0.20=py310_cu11.8.0_pyt2.0.1
- xkeyboard-config=2.38=h0b41bf4_0
- xorg-kbproto=1.0.7=h7f98852_1002
- xorg-libice=1.1.1=hd590300_0
- xorg-libsm=1.2.4=h7391055_0
- xorg-libx11=1.8.4=h0b41bf4_0
- xorg-libxau=1.0.11=hd590300_0
- xorg-libxdmcp=1.1.3=h7f98852_0
- xorg-libxext=1.3.4=h0b41bf4_2
- xorg-libxrender=0.9.10=h7f98852_1003
- xorg-renderproto=0.11.1=h7f98852_1002
- xorg-xextproto=7.3.0=h0b41bf4_1003
- xorg-xproto=7.0.31=h7f98852_1007
- xxhash=0.8.1=h0b41bf4_0
- xz=5.2.6=h166bdaf_0
- yaml=0.2.5=h7f98852_2
- yarl=1.9.2=py310h2372a71_0
- zeromq=4.3.4=h9c3ff4c_1
- zipp=3.15.0=pyhd8ed1ab_0
- zlib=1.2.13=hd590300_5
- zstd=1.5.2=h3eb15da_6

